version: '3.8'

services:
  laravel-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel_network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - laravel-app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
