name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull ptuan123987/laravel-udemy:latest

    - name: Delete Old Docker Container
      run: |
        if [ $(sudo docker ps -a -q -f name=cicd-pipeline-container) ]; then
          sudo docker rm -f cicd-pipeline-container
        fi

    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name cicd-pipeline-container ptuan123987/laravel-udemy:latest
